plugins:
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'vendor/**/*'
    - 'config/environments/*'

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false